nelmio_api_doc:
    documentation:
        info:
            title: My Todo app
            description: This is an awesome app!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)