version: '3.7'

services:
    db:
        container_name: db_todo
        image: mysql:8
        command: ["--default-authentication-plugin=mysql_native_password"]
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - db_todo

volumes:
    db_app:

networks:
    db_todo:

